services:
  - type: web
    name: planistry
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: |
      python manage.py migrate --noinput &&
      gunicorn planistry.wsgi:application

    envVars:
      - key: DJANGO_SECRET_KEY
        value: "ضع هنا secret key الجديدة"

      - key: DATABASE_URL
        fromDatabase:
          name: planistry-db
          property: connectionString

      - key: DJANGO_SETTINGS_MODULE
        value: planistry.settings
