services:
  - type: web
    name: planistry
    env: python
    buildCommand: "./manage.py migrate && pip install -r requirements.txt"
    startCommand: "gunicorn planistry.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: planistry-db
          property: connectionString
      - key: DJANGO_SETTINGS_MODULE
        value: "planistry.settings"
