services:
  - type: web
    name: planistry
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: |
      python manage.py migrate --noinput &&
      gunicorn planistry.wsgi:application

    envVars:
      - key: DJANGO_SECRET_KEY
        value: "@@^!dbk*ac$+qx$wqp)_=5!@ik=t6n42o4&87=l)1@n4e=7ekt"

      - key: DATABASE_URL
        fromDatabase:
          name: planistry
          property: connectionString

      - key: DJANGO_SETTINGS_MODULE
        value: planistry.settings
