# Generated by Django 5.1.6 on 2025-03-04 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academic", "0002_initial"),
        ("study_plans", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="progress",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="progress_records",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="studyplan",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="study_plans",
                to="academic.course",
            ),
        ),
        migrations.AddField(
            model_name="studyplan",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="study_plans",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="progress",
            name="study_plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="progress_records",
                to="study_plans.studyplan",
            ),
        ),
        migrations.AddField(
            model_name="goal",
            name="study_plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="goals",
                to="study_plans.studyplan",
            ),
        ),
        migrations.AddField(
            model_name="studysession",
            name="study_plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="study_sessions",
                to="study_plans.studyplan",
            ),
        ),
        migrations.AddField(
            model_name="studytask",
            name="completed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="completed_tasks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="studytask",
            name="parent_task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subtasks",
                to="study_plans.studytask",
            ),
        ),
        migrations.AddField(
            model_name="studytask",
            name="prerequisites",
            field=models.ManyToManyField(
                blank=True, related_name="dependent_tasks", to="study_plans.studytask"
            ),
        ),
        migrations.AddField(
            model_name="studytask",
            name="study_plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="study_plans.studyplan",
            ),
        ),
    ]
