# Generated by Django 5.2 on 2025-04-09 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursefile",
            name="size",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
