# Generated by Django 5.2 on 2025-04-22 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0002_alter_coursefile_size"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coursefile",
            name="upload_date",
        ),
        migrations.AddField(
            model_name="coursefile",
            name="filename",
            field=models.CharField(default="unknown_filename", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="coursefile",
            name="file",
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name="coursefile",
            name="updated_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
